networks:
  shield-network:
    driver: bridge

services:
  db-users:
    image: postgres:15-alpine
    container_name: db-users
    networks:
      - shield-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./.docker-data/postgres:/var/lib/postgresql/data

  db-ledger:
    image: codenotary/immudb:latest
    container_name: db-ledger
    networks:
      - shield-network
    environment:
      IMMUDB_ADMIN_PASSWORD: ${IMMUDB_ADMIN_PASSWORD}
    ports:
      - "3322:3322"
      - "8080:8080"
    volumes:
      - ./.docker-data/immudb:/var/lib/immudb

  minio-store:
    image: minio/minio
    container_name: minio-store
    networks:
      - shield-network
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./.docker-data/minio:/data

  shield-gateway:
    build: ./shield-gateway
    container_name: shield-gateway
    command: npm run dev
    volumes:
      - /usr/src/app/node_modules
    develop:
      watch:
        - action: sync
          path: ./shield-gateway
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./shield-gateway/package.json
    networks:
      - shield-network
    ports:
      - "3001:3000"
    depends_on:
      - shield-auth
      - shield-evidence

  shield-frontend:
    build: ./shield-frontend
    container_name: shield-frontend
    command: npm run dev
    volumes:
      - /usr/src/app/node_modules
    develop:
      watch:
        - action: sync
          path: ./shield-frontend
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./shield-frontend/package.json
    networks:
      - shield-network
    ports:
      - "3000:3000"
    depends_on:
      - shield-gateway

  shield-auth:
    build: ./shield-auth
    container_name: shield-auth
    command: npm run dev
    volumes:
      - /usr/src/app/node_modules
    develop:
      watch:
        - action: sync
          path: ./shield-auth
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./shield-auth/package.json
    networks:
      - shield-network
    expose:
      - "4000"
    environment:
      DB_HOST: db-users
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db-users

  shield-evidence:
    build: ./shield-evidence
    container_name: shield-evidence
    command: npm run dev
    volumes:
      - /usr/src/app/node_modules
    develop:
      watch:
        - action: sync
          path: ./shield-evidence
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./shield-evidence/package.json
    networks:
      - shield-network
    expose:
      - "4001"
    env_file:
      - ./shield-evidence/.env.docker
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      MASTER_KEY: ${MASTER_KEY}
    depends_on:
      - minio-store
      - shield-ledger

  shield-ledger:
    build: ./shield-ledger
    container_name: shield-ledger
    command: npm run dev
    volumes:
      - /usr/src/app/node_modules
    develop:
      watch:
        - action: sync
          path: ./shield-ledger
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./shield-ledger/package.json
    networks:
      - shield-network
    expose:
      - "4002"
    environment:
      IMMUDB_HOST: db-ledger
      IMMUDB_USER: ${IMMUDB_USER}
      IMMUDB_ADMIN_PASSWORD: ${IMMUDB_ADMIN_PASSWORD}
    depends_on:
      - db-ledger
